"""`input_dim` and `num_classes` name the same thing twice, and must agree.

Both are fields on `DataConfig` and on `ModelConfig`, populated independently:
`_data_config` reads only `config.data.*` and `_model_config` only
`config.model.*`. Nothing compared them, so an edit to one block without the
other gave either a shape-mismatch traceback from inside a builder or, for
`num_classes` set high, output units that are never predicted and never
mentioned. P11-F01.

The comparison is against the dataset's own `get_metadata()`, not against
`config.data.*`: only `configs/dev/synthetic.yaml` and the two smoke configs
set both blocks, while every manifest-backed config leaves `data.*` unset
because the dimensions live in the manifest. So this guard checks both --
the in-memory backend, where the metadata *is* `config.data.*`, and the
manifest-backed one, where it is the file on disk.

That file is generated here, into a scratch tree, from the generator config
that ships beside the run config. These tests used to read `data/generated/`,
which is gitignored and absent from a clone: the refusal test was red in every
clone, the clean-config test passed while comparing nothing, and the
shipped-config sweep was green only when an earlier test in the same run had
generated a dataset there.
"""

from __future__ import annotations

import json
import tempfile
import unittest
from pathlib import Path
from typing import Any

import pytest
import yaml

from fedbrew.core.config import load_config
from fedbrew.core.factory import (
    SHARED_SHAPE_FIELDS,
    _model_config,
    build_components,
    model_data_shape_mismatch,
)
from fedbrew.core.validation import validate_full_config
from fedbrew.data.generate import generate_from_config

CODE = "model.data_shape_mismatch"

#: Generators whose shipped configs read input a clone does not contain, so
#: their datasets cannot be generated inside a test. Every other generator
#: config under `data/configs/` is generated by `GeneratedDataTestCase`.
NEEDS_EXTERNAL_INPUT = {
    "femnist": "downloads its source from the Hugging Face Hub",
    "generic_sft": "reads dataset assets prepared under data/raw/",
    "hf_causal_lm_text": "reads a corpus under data/raw/",
    "mnist": "downloads MNIST into data/raw/",
    "oasst1_sft": "reads dataset assets prepared under data/raw/",
    "tiny_causal_lm": "reads a corpus under data/raw/",
}

#: Manifests a shipped run config names that no generator config writes.
NO_GENERATOR_CONFIG = {
    Path("data/generated/openimage_96/manifest.json"): "nothing under data/configs/ writes it",
}


def _run_configs() -> list[Path]:
    """Every shipped run config: the ones carrying a `runtime` block."""

    paths = []
    for path in sorted(Path("configs").rglob("*.yaml")):
        loaded = yaml.safe_load(path.read_text(encoding="utf-8"))
        if isinstance(loaded, dict) and "runtime" in loaded:
            paths.append(path)
    return paths


def _generator_configs() -> dict[Path, dict[str, Any]]:
    """Every generator config under `data/configs/`, keyed by the manifest it writes."""

    found = {}
    for path in sorted(Path("data/configs").rglob("*.yaml")):
        loaded = yaml.safe_load(path.read_text(encoding="utf-8"))
        dataset = loaded.get("dataset") if isinstance(loaded, dict) else None
        if isinstance(dataset, dict) and "output_dir" in dataset:
            found[Path(dataset["output_dir"]) / "manifest.json"] = loaded
    return found


class GeneratedDataTestCase(unittest.TestCase):
    """Generates every dataset a clone can, from the generator config that ships it.

    Into a scratch tree rather than `data/generated/`, so what a test compares
    against is what this tree's generators write rather than whatever an earlier
    test or run left there, and so the suite never replaces a dataset a real run
    may be reading. `generated` maps each shipped manifest path to its copy.
    """

    generated: dict[Path, Path]

    @classmethod
    def setUpClass(cls) -> None:
        cls._scratch = tempfile.TemporaryDirectory()
        cls.generated = {}
        for index, (shipped, config) in enumerate(sorted(_generator_configs().items())):
            if config["dataset"]["name"] in NEEDS_EXTERNAL_INPUT:
                continue
            config["dataset"]["output_dir"] = str(Path(cls._scratch.name) / str(index))
            path = Path(cls._scratch.name) / f"{index}.yaml"
            path.write_text(yaml.safe_dump(config), encoding="utf-8")
            cls.generated[shipped] = Path(generate_from_config(path))

    @classmethod
    def tearDownClass(cls) -> None:
        cls._scratch.cleanup()


class ShippedConfigsAgreeWithTheirDataTest(GeneratedDataTestCase):
    def test_no_shipped_config_is_sized_for_other_data(self) -> None:
        """The audit's `currently consistent` finding, now enforced.

        A config whose data a clone cannot generate is declared, through its
        generator in `NEEDS_EXTERNAL_INPUT` or its path in
        `NO_GENERATOR_CONFIG`. One declared in neither fails here rather than
        dropping out of the sweep, so the set this checks cannot quietly shrink.
        """

        generators = _generator_configs()
        checked = 0
        unclassified = []
        for path in _run_configs():
            config = load_config(str(path))
            if config.data.name != "manifest_dataset" or not config.data.path:
                continue
            shipped = Path(config.data.path)
            if shipped in self.generated:
                checked += 1
                manifest = json.loads(self.generated[shipped].read_text(encoding="utf-8"))
                with self.subTest(config=str(path)):
                    self.assertIsNone(
                        model_data_shape_mismatch(_model_config(config), manifest),
                    )
            elif shipped not in NO_GENERATOR_CONFIG and (
                shipped not in generators
                or generators[shipped]["dataset"]["name"] not in NEEDS_EXTERNAL_INPUT
            ):
                unclassified.append(str(path))
        self.assertEqual(unclassified, [], "data neither generated here nor declared out of reach")
        self.assertGreater(checked, 0, "no dataset was generated; the guard checked nothing")

    def test_at_least_one_shipped_config_declares_each_shared_field(self) -> None:
        """A field no config sets is a comparison that never runs."""

        declared: set[str] = set()
        for path in _run_configs():
            declared |= set(_model_config(load_config(str(path)))) & set(SHARED_SHAPE_FIELDS)
        self.assertEqual(declared, set(SHARED_SHAPE_FIELDS))


@pytest.mark.fast
class TheInMemoryBackendIsCheckedTest(unittest.TestCase):
    """`configs/dev/synthetic.yaml` is the one config that sets both blocks."""

    def _config(self) -> Any:
        config = load_config("configs/dev/synthetic.yaml")
        self.assertEqual(
            (config.data.input_dim, config.data.num_classes),
            (config.model.input_dim, config.model.num_classes),
            "the config this test drifts from is already drifted",
        )
        return config

    def test_the_agreeing_config_builds(self) -> None:
        build_components(self._config())

    def test_a_drifted_input_dim_is_refused(self) -> None:
        config = self._config()
        config.model.input_dim = config.data.input_dim + 4
        with self.assertRaises(ValueError) as caught:
            build_components(config)
        self.assertIn("model.input_dim", str(caught.exception))

    def test_num_classes_set_high_is_refused(self) -> None:
        """The silent half: unused output units, no error and no log line."""

        config = self._config()
        config.model.num_classes = config.data.num_classes + 5
        with self.assertRaises(ValueError) as caught:
            build_components(config)
        self.assertIn("model.num_classes", str(caught.exception))


class PreflightReportsTheSameRefusalTest(GeneratedDataTestCase):
    CONFIG = "configs/dev/synthetic_label_skew.yaml"

    def _config(self) -> Any:
        """The shipped config, reading the dataset `setUpClass` generated for it."""

        config = load_config(self.CONFIG)
        config.data.path = str(self.generated[Path(config.data.path)])
        return config

    def _errors(self, config: Any) -> list[str]:
        return [
            issue.message for issue in validate_full_config(config).issues if issue.code == CODE
        ]

    def test_a_shipped_manifest_config_is_clean(self) -> None:
        """With no manifest on disk this compared nothing, and passed with
        `model.num_classes` raised from 3 to 6 in the shipped config."""

        self.assertEqual(self._errors(self._config()), [])

    def test_preflight_reports_what_the_build_would_raise(self) -> None:
        for field in SHARED_SHAPE_FIELDS:
            with self.subTest(field=field):
                config = self._config()
                setattr(config.model, field, getattr(config.model, field) + 3)
                with self.assertRaises(ValueError) as caught:
                    build_components(config)
                self.assertEqual(self._errors(config), [str(caught.exception)])


@pytest.mark.fast
class WhatIsNotADisagreementTest(unittest.TestCase):
    def test_a_key_only_one_side_declares_is_not_compared(self) -> None:
        """femnist_resnet18 takes no input_dim; a manifest may omit one too."""

        self.assertIsNone(model_data_shape_mismatch({"num_classes": 62}, {"num_classes": 62}))
        self.assertIsNone(model_data_shape_mismatch({"input_dim": 784}, {"num_classes": 10}))
        self.assertIsNone(model_data_shape_mismatch({}, {"input_dim": 784}))

    def test_a_sequence_shape_compares_by_value_not_by_type(self) -> None:
        """MNIST writes 784 when flatten is on and [1, 28, 28] when it is not."""

        self.assertIsNone(
            model_data_shape_mismatch({"input_dim": (1, 28, 28)}, {"input_dim": [1, 28, 28]})
        )
        self.assertIsNotNone(
            model_data_shape_mismatch({"input_dim": 784}, {"input_dim": [1, 28, 28]})
        )

    def test_every_shared_field_is_actually_compared(self) -> None:
        for field in SHARED_SHAPE_FIELDS:
            with self.subTest(field=field):
                self.assertIsNotNone(model_data_shape_mismatch({field: 1}, {field: 2}))


if __name__ == "__main__":
    unittest.main()
