model_identifier: Qwen/Qwen2.5-0.5B-Instruct
tokenizer_identifier: Qwen/Qwen2.5-0.5B-Instruct
revision: 7ae557604adf67be50417f59c2c2f167def9a775
cache_dir: $FL_CACHE_ROOT/models/qwen2_5_0_5b_instruct
