"""Dataset-agnostic supervised fine-tuning generator.

Turns any prepared Hugging Face dataset whose rows carry a prompt, a response,
and a natural client key into federated causal-LM SFT shards. Tokenization,
prompt masking, packing, and manifest format are shared with ``oasst1_sft`` so
datasets generated by either module are directly comparable.

Rows are mapped to a single user/assistant exchange through configured string
templates, so adding a dataset is a config file rather than a code change.
"""

from __future__ import annotations

import csv
import hashlib
import json
import random
from collections import Counter, defaultdict
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any, cast

from torch import Tensor

from fedbrew.core.paths import expand_path
from fedbrew.data.oasst1_sft import (
    IGNORE_INDEX,
    ChatMessage,
    TokenizedSFTExample,
    TokenizerContractError,
    TokenizerTrace,
    anonymize_client_id,
    assign_tree_split,
    pack_sft_examples,
    tokenize_assistant_target,
)
from fedbrew.data.writers.manifest import save_clients_jsonl, save_manifest
from fedbrew.data.writers.torch_shards import (
    save_client_shard,
    save_split_client_shard,
)

DEFAULT_SEQUENCE_LENGTH = 512
DEFAULT_SPLIT_RATIOS = (0.8, 0.1, 0.1)


@dataclass(frozen=True, slots=True)
class GenericSFTGenerationSummary:
    """Summary returned to the generic generator CLI."""

    manifest_path: Path
    num_clients: int
    num_examples: int
    num_test_examples: int


@dataclass(frozen=True, slots=True)
class FieldMapping:
    """How one dataset's rows become a prompt/response pair for one client."""

    prompt_template: str
    response_template: str
    client_field: str
    group_field: str
    required_fields: tuple[str, ...]
    choice: Mapping[str, Any] | None
    anonymize_client_ids: bool
    system_prompt: str | None


@dataclass(frozen=True, slots=True)
class PreparedRow:
    """One tokenized example with the split and client it belongs to."""

    client_key: str
    split: str
    example: TokenizedSFTExample


def generate_generic_sft_from_config(
    *,
    config: Mapping[str, Any],
    output_dir: Path,
    seed: int,
    client_splits: Mapping[str, float] | None = None,
) -> GenericSFTGenerationSummary:
    """Generate federated SFT shards from a prepared dataset snapshot."""

    # Part of the shards ABI (chapter 12 §4), and unread here: the ratios come
    # from `tree_splits`, as in oasst1_sft. A config that sets `client_splits`
    # is refused by name -- generic_sft does not declare it on its
    # GeneratorSpec -- so this never silently overrides anything.
    del client_splits

    sft_config = _mapping(config.get("generic_sft"), "generic_sft")
    mapping = _parse_field_mapping(sft_config)
    sequence_length = _positive_int(
        sft_config.get("sequence_length", DEFAULT_SEQUENCE_LENGTH),
        "generic_sft.sequence_length",
    )
    ignore_index = int(sft_config.get("ignore_index", IGNORE_INDEX))
    _require_offline(sft_config)

    ratios = _parse_split_ratios(config.get("tree_splits"))
    partition = _mapping(config.get("partition"), "partition")
    num_clients = _positive_int(partition.get("num_clients", 20), "partition.num_clients")
    caps = _mapping(config.get("caps"), "caps")

    dataset_manifest_path, dataset_manifest = _load_dataset_assets(sft_config)
    tokenizer_trace = _resolve_tokenizer_assets(sft_config)
    tokenizer = _load_tokenizer(tokenizer_trace)
    eos_token_id = _eos_token_id(tokenizer)

    rows = _load_dataset_rows(dataset_manifest)
    prepared, counts = _prepare_rows(
        rows,
        mapping=mapping,
        tokenizer=tokenizer,
        seed=seed,
        ratios=ratios,
    )

    selected, client_windows, global_test = _build_shards(
        prepared,
        seed=seed,
        mapping=mapping,
        num_clients=num_clients,
        sequence_length=sequence_length,
        eos_token_id=eos_token_id,
        ignore_index=ignore_index,
        caps=caps,
    )

    return _write_outputs(
        output_dir=output_dir,
        seed=seed,
        selected=selected,
        client_windows=client_windows,
        global_test=global_test,
        mapping=mapping,
        counts=counts,
        ratios=ratios,
        sequence_length=sequence_length,
        ignore_index=ignore_index,
        eos_token_id=eos_token_id,
        tokenizer_trace=tokenizer_trace,
        dataset_manifest=dataset_manifest,
        dataset_manifest_path=dataset_manifest_path,
        caps=caps,
        num_clients=num_clients,
    )


def render_template(template: str, row: Mapping[str, Any]) -> str:
    """Substitute ``{field}`` placeholders from one dataset row."""

    try:
        return template.format(**row).strip()
    except KeyError as exc:
        raise ValueError(
            f"template references field {exc.args[0]!r} which the dataset does not provide"
        ) from exc


def resolve_choice_fields(
    row: Mapping[str, Any],
    choice: Mapping[str, Any] | None,
) -> dict[str, Any]:
    """Return ``answer_label``/``answer_text`` for multiple-choice datasets."""

    if choice is None:
        return {}
    index_field = str(choice["index_field"])
    option_fields = [str(name) for name in choice["option_fields"]]
    labels = [str(label) for label in choice.get("labels", [])]
    if labels and len(labels) != len(option_fields):
        raise ValueError("choice.labels must match choice.option_fields in length")
    raw_index = row.get(index_field)
    if raw_index is None or isinstance(raw_index, bool):
        raise ValueError(f"choice.index_field {index_field!r} is missing")
    index = int(raw_index)
    if not 0 <= index < len(option_fields):
        raise ValueError(
            f"choice index {index} is outside the configured {len(option_fields)} options"
        )
    label = labels[index] if labels else str(index)
    return {"answer_label": label, "answer_text": str(row.get(option_fields[index], ""))}


def _prepare_rows(
    rows: Sequence[Mapping[str, Any]],
    *,
    mapping: FieldMapping,
    tokenizer: Any,
    seed: int,
    ratios: tuple[float, float, float],
) -> tuple[list[PreparedRow], dict[str, int]]:
    counts = Counter[str]()
    counts["source_rows"] = len(rows)
    prepared: list[PreparedRow] = []
    for row_number, row in enumerate(rows, start=1):
        client_key = _text_or_none(row.get(mapping.client_field))
        group_key = _text_or_none(row.get(mapping.group_field))
        if client_key is None or group_key is None:
            counts["rows_missing_client_or_group_key"] += 1
            continue
        if any(_text_or_none(row.get(field)) is None for field in mapping.required_fields):
            counts["rows_missing_required_fields"] += 1
            continue
        try:
            values = dict(row)
            values.update(resolve_choice_fields(row, mapping.choice))
            prompt = render_template(mapping.prompt_template, values)
            response = render_template(mapping.response_template, values)
        except ValueError:
            counts["rows_failing_template_rendering"] += 1
            continue
        if not prompt or not response:
            counts["rows_with_empty_prompt_or_response"] += 1
            continue

        messages: list[ChatMessage] = []
        if mapping.system_prompt:
            messages.append(ChatMessage(role="system", content=mapping.system_prompt))
        messages.append(ChatMessage(role="user", content=prompt))
        messages.append(ChatMessage(role="assistant", content=response))
        try:
            example = tokenize_assistant_target(messages, tokenizer)
        except TokenizerContractError as exc:
            # Not skippable. The prompt-prefix guard is what makes the label
            # mask correct, so a tokenizer or template that breaks it breaks
            # every example, not this row: swallowing it into a counter turns
            # a broken masking contract into a quietly smaller dataset with
            # prompt tokens counted in the loss. Fail with the row that hit
            # it and how far the pass had got.
            raise TokenizerContractError(
                f"{exc} (source row {row_number} of {len(rows)}; "
                f"{counts['qualifying_rows']} rows tokenized cleanly before "
                "it). This is a property of the tokenizer and its chat "
                "template, not of the row, so the rows already accepted are "
                "masked wrongly too."
            ) from exc
        except ValueError:
            # A property of this row's own text -- an empty assistant target
            # after templating. Skipping it is correct; the count reaches
            # manifest.filtering_summary.
            counts["rows_failing_tokenization"] += 1
            continue

        counts["qualifying_rows"] += 1
        prepared.append(
            PreparedRow(
                client_key=client_key,
                split=assign_tree_split(
                    group_key,
                    seed=seed,
                    train_ratio=ratios[0],
                    client_eval_ratio=ratios[1],
                    global_test_ratio=ratios[2],
                ),
                example=example,
            )
        )
    return prepared, dict(counts)


def _build_shards(
    prepared: Sequence[PreparedRow],
    *,
    seed: int,
    mapping: FieldMapping,
    num_clients: int,
    sequence_length: int,
    eos_token_id: int,
    ignore_index: int,
    caps: Mapping[str, Any],
) -> tuple[list[str], dict[str, dict[str, tuple[Tensor, Tensor]]], tuple[Tensor, Tensor]]:
    by_client: dict[str, dict[str, list[TokenizedSFTExample]]] = defaultdict(
        lambda: {"train": [], "client_eval": []}
    )
    global_test: list[TokenizedSFTExample] = []
    for item in prepared:
        if item.split == "global_test":
            global_test.append(item.example)
        else:
            by_client[item.client_key][item.split].append(item.example)

    # Ranking key, taken before train_fraction so that a config which drops no
    # client selects exactly the clients it did before.
    train_tokens = {
        client: sum(e.target_token_count for e in splits["train"])
        for client, splits in by_client.items()
    }

    train_fraction = _fraction(caps.get("train_fraction"))
    if train_fraction is not None:
        # Scale every client by the same factor so the natural size imbalance
        # between clients is preserved exactly; a flat window cap would erase it.
        for client, splits in by_client.items():
            examples = list(splits["train"])
            random.Random(f"{seed}:{client}").shuffle(examples)
            keep = max(1, int(round(len(examples) * train_fraction)))
            splits["train"] = examples[:keep]

    train_cap = _optional_positive_int(caps.get("train_windows_per_client"))
    eval_cap = _optional_positive_int(caps.get("client_eval_windows_per_client"))
    test_cap = _optional_positive_int(caps.get("global_test_windows"))

    # Eligibility is decided on the packed windows, not on the rows that went
    # in. pack_sft_examples drops any window that is not full, so a client
    # whose eval rows total fewer than sequence_length + 1 tokens packs to zero
    # eval windows -- and train_fraction, applied above, can do the same to its
    # train side. Selecting on row counts wrote such a client into the dataset
    # with num_eval_examples: 0 and said nothing. oasst1_sft.py:235 already
    # decides this after packing; this is the same order.
    packed: dict[str, dict[str, tuple[Tensor, Tensor]]] = {}
    empty: dict[str, list[str]] = {}
    for client, splits in by_client.items():
        windows = {
            "train": pack_sft_examples(
                splits["train"],
                eos_token_id=eos_token_id,
                sequence_length=sequence_length,
                ignore_index=ignore_index,
                max_windows=train_cap,
            ),
            "eval": pack_sft_examples(
                splits["client_eval"],
                eos_token_id=eos_token_id,
                sequence_length=sequence_length,
                ignore_index=ignore_index,
                max_windows=eval_cap,
            ),
        }
        missing = [name for name, (_, y) in windows.items() if y.shape[0] == 0]
        if missing:
            empty[client] = missing
            continue
        packed[client] = windows

    if len(packed) < num_clients:
        detail = ""
        if empty:
            empty_summary = ", ".join(
                f"{client} has no {' or '.join(missing)} window"
                for client, missing in sorted(empty.items())[:3]
            )
            detail = (
                f" {len(empty)} client(s) packed to zero windows in a split "
                f"({empty_summary}); their rows total fewer than sequence_length + 1 "
                f"= {sequence_length + 1} tokens, so every window was incomplete "
                "and dropped."
            )
        raise ValueError(
            f"only {len(packed)} clients have both train and evaluation "
            f"windows; partition.num_clients={num_clients} cannot be "
            f"satisfied.{detail}"
        )

    selected = sorted(
        packed,
        key=lambda client: (
            -train_tokens[client],
            hashlib.sha256(client.encode()).hexdigest(),
        ),
    )[:num_clients]
    client_windows = {client: packed[client] for client in selected}
    packed_test = pack_sft_examples(
        global_test,
        eos_token_id=eos_token_id,
        sequence_length=sequence_length,
        ignore_index=ignore_index,
        max_windows=test_cap,
    )
    if packed_test[0].shape[0] == 0:
        raise ValueError("no global-test windows were produced; reduce sequence_length")
    del mapping
    return selected, client_windows, packed_test


def _write_outputs(
    *,
    output_dir: Path,
    seed: int,
    selected: Sequence[str],
    client_windows: Mapping[str, Mapping[str, tuple[Tensor, Tensor]]],
    global_test: tuple[Tensor, Tensor],
    mapping: FieldMapping,
    counts: Mapping[str, int],
    ratios: tuple[float, float, float],
    sequence_length: int,
    ignore_index: int,
    eos_token_id: int,
    tokenizer_trace: TokenizerTrace,
    dataset_manifest: Any,
    dataset_manifest_path: Path,
    caps: Mapping[str, Any],
    num_clients: int,
) -> GenericSFTGenerationSummary:
    shards_dir = output_dir / "shards"
    shards_dir.mkdir(parents=True, exist_ok=True)

    client_ids = _client_ids(selected, mapping)

    client_records: list[dict[str, Any]] = []
    stats_rows: list[dict[str, Any]] = []
    total_examples = 0
    for client_key in selected:
        client_id = client_ids[client_key]
        train_x, train_y = client_windows[client_key]["train"]
        eval_x, eval_y = client_windows[client_key]["eval"]
        shard_name = f"{client_id}.pt"
        save_split_client_shard(shards_dir / shard_name, train_x, train_y, eval_x, eval_y)
        total_examples += int(train_x.shape[0]) + int(eval_x.shape[0])
        client_records.append(
            {
                "client_id": client_id,
                "shard": f"shards/{shard_name}",
                "num_examples": int(train_x.shape[0]) + int(eval_x.shape[0]),
                "num_train_examples": int(train_x.shape[0]),
                "num_eval_examples": int(eval_x.shape[0]),
            }
        )
        stats_rows.append(
            {
                "client_id": client_id,
                "client_key": "" if mapping.anonymize_client_ids else client_key,
                "num_examples": int(train_x.shape[0]) + int(eval_x.shape[0]),
                "num_train_examples": int(train_x.shape[0]),
                "num_eval_examples": int(eval_x.shape[0]),
                "num_train_tokens": int(train_x.numel()),
                "num_eval_tokens": int(eval_x.numel()),
                "train_active_target_tokens": int((train_y != ignore_index).sum()),
                "eval_active_target_tokens": int((eval_y != ignore_index).sum()),
            }
        )

    test_x, test_y = global_test
    save_client_shard(shards_dir / "global_test.pt", test_x, test_y)

    save_clients_jsonl(output_dir, client_records)
    _write_stats(output_dir, stats_rows)

    manifest = {
        "dataset_name": "generic_sft",
        "task": "causal_lm_sft",
        "format": "torch_shards",
        "client_shard_format": "split",
        "shards_dir": "shards",
        "clients_file": "clients.jsonl",
        "client_stats_file": "client_stats.csv",
        "global_test": "shards/global_test.pt",
        "num_clients": len(selected),
        "selected_client_ids": [record["client_id"] for record in client_records],
        "sequence_length": sequence_length,
        "stride": sequence_length,
        "input_shape": [sequence_length],
        "input_dtype": "int64",
        "target_dtype": "int64",
        "ignore_index": ignore_index,
        "eos_token_id": eos_token_id,
        "padding_token_id": None,
        "packing": "fixed_non_overlapping_eos_separated_drop_incomplete",
        "vocab_size": tokenizer_trace.vocabulary_size,
        "tokenizer_vocabulary_size": tokenizer_trace.vocabulary_size,
        "tokenizer": str(tokenizer_trace.path),
        "tokenizer_asset_path": str(tokenizer_trace.path),
        "tokenizer_asset_manifest": str(tokenizer_trace.manifest_path),
        "tokenizer_identifier": tokenizer_trace.identifier,
        "tokenizer_requested_revision": tokenizer_trace.requested_revision,
        "tokenizer_resolved_revision": tokenizer_trace.resolved_revision,
        "tokenizer_revision": tokenizer_trace.resolved_revision,
        "dataset_asset_manifest": str(dataset_manifest_path),
        "asset_manifest": str(tokenizer_trace.manifest_path),
        "source_file_hashes": dict(dataset_manifest.source_hashes),
        "corpus_hash": _corpus_hash(dataset_manifest.source_hashes, mapping),
        "source_dataset_identifier": dataset_manifest.dataset_identifier,
        "source_dataset_requested_revision": dataset_manifest.requested_revision,
        "source_dataset_resolved_revision": dataset_manifest.resolved_revision,
        "source_dataset_revision": dataset_manifest.resolved_revision,
        "partition_strategy": "natural_field_top_target_tokens",
        "partition_field": mapping.client_field,
        "group_field": mapping.group_field,
        "client_ids_anonymized": mapping.anonymize_client_ids,
        "prompt_template": mapping.prompt_template,
        "response_template": mapping.response_template,
        "system_prompt": mapping.system_prompt,
        "required_fields": list(mapping.required_fields),
        "split_ratios": {
            "train": ratios[0],
            "client_eval": ratios[1],
            "global_test": ratios[2],
        },
        "tree_split_policy": "sha256(seed:group_field), deterministic",
        "tree_split_key": mapping.group_field,
        "filtering_summary": dict(counts),
        "caps": dict(caps),
        "train_subsample_fraction": _fraction(caps.get("train_fraction")),
        "requested_num_clients": num_clients,
        "global_test_num_examples": int(test_x.shape[0]),
        "global_test_active_target_tokens": int((test_y != ignore_index).sum()),
        "seed": seed,
        "local_files_only": True,
        "offline": True,
        "trust_remote_code": False,
        "partition_stats_file": "partition_stats.json",
    }
    manifest_path = save_manifest(output_dir, manifest)
    _write_partition_stats(output_dir, stats_rows, manifest)

    return GenericSFTGenerationSummary(
        manifest_path=manifest_path,
        num_clients=len(selected),
        num_examples=total_examples,
        num_test_examples=int(test_x.shape[0]),
    )


def _write_stats(output_dir: Path, rows: Sequence[Mapping[str, Any]]) -> None:
    path = output_dir / "client_stats.csv"
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)


def _write_partition_stats(
    output_dir: Path,
    rows: Sequence[Mapping[str, Any]],
    manifest: Mapping[str, Any],
) -> None:
    stats = {
        "dataset_name": "generic_sft",
        "task": "causal_lm_sft",
        "partition_strategy": manifest["partition_strategy"],
        "partition_field": manifest["partition_field"],
        "num_clients": manifest["num_clients"],
        "split_ratios": manifest["split_ratios"],
        "total_examples": sum(int(row["num_examples"]) for row in rows),
        "total_tokens": sum(
            int(row["num_train_tokens"]) + int(row["num_eval_tokens"]) for row in rows
        ),
        "total_active_target_tokens": sum(
            int(row["train_active_target_tokens"]) + int(row["eval_active_target_tokens"])
            for row in rows
        ),
        "global_test_examples": manifest["global_test_num_examples"],
        "global_test_active_target_tokens": manifest["global_test_active_target_tokens"],
        "clients": list(rows),
    }
    (output_dir / "partition_stats.json").write_text(
        json.dumps(stats, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )


def _corpus_hash(
    source_hashes: Mapping[str, str],
    mapping: FieldMapping,
) -> str:
    """Hash the source splits together with the mapping that produced the corpus.

    Two datasets built from the same snapshot but different templates are
    different corpora, so the templates belong in the identity.
    """

    digest = hashlib.sha256()
    for split, value in sorted(source_hashes.items()):
        digest.update(f"{split}:{value}\n".encode())
    for name, value in (
        ("prompt_template", mapping.prompt_template),
        ("response_template", mapping.response_template),
        ("system_prompt", mapping.system_prompt or ""),
        ("client_field", mapping.client_field),
        ("group_field", mapping.group_field),
        ("required_fields", ",".join(mapping.required_fields)),
        ("choice", json.dumps(mapping.choice, sort_keys=True)),
    ):
        digest.update(f"{name}:{value}\n".encode())
    return digest.hexdigest()


def _parse_field_mapping(sft_config: Mapping[str, Any]) -> FieldMapping:
    prompt_template = _required_text(sft_config, "prompt_template")
    response_template = _required_text(sft_config, "response_template")
    client_field = _required_text(sft_config, "client_field")
    group_field = _required_text(sft_config, "group_field")
    required = sft_config.get("required_fields", ())
    if isinstance(required, str) or not isinstance(required, Sequence):
        raise ValueError("generic_sft.required_fields must be a list")
    choice = sft_config.get("choice")
    if choice is not None:
        choice = _mapping(choice, "generic_sft.choice")
        for key in ("index_field", "option_fields"):
            if key not in choice:
                raise ValueError(f"generic_sft.choice requires {key}")
    system_prompt = sft_config.get("system_prompt")
    return FieldMapping(
        prompt_template=prompt_template,
        response_template=response_template,
        client_field=client_field,
        group_field=group_field,
        required_fields=tuple(str(name) for name in required),
        choice=choice,
        anonymize_client_ids=bool(sft_config.get("anonymize_client_ids", True)),
        system_prompt=str(system_prompt) if system_prompt else None,
    )


def _load_dataset_assets(sft_config: Mapping[str, Any]) -> tuple[Path, Any]:
    manifest_value = sft_config.get("dataset_asset_manifest")
    if not manifest_value:
        raise ValueError("generic_sft requires generic_sft.dataset_asset_manifest")
    manifest_path = expand_path(str(manifest_value))
    preparation_config = sft_config.get("dataset_preparation_config")
    from fedbrew.data.asset_manifest import load_dataset_asset_manifest

    manifest = load_dataset_asset_manifest(
        manifest_path,
        preparation_config=(str(preparation_config) if preparation_config else None),
        require_files=True,
        verify_hashes=True,
    )
    return manifest_path, manifest


def _load_dataset_rows(manifest: Any) -> list[Mapping[str, Any]]:
    import pyarrow.parquet as parquet  # type: ignore[import-untyped]

    rows: list[Mapping[str, Any]] = []
    for split in ("train", "validation"):
        source = manifest.file_for_split(split)
        table = parquet.read_table(source.local_path)
        split_rows = cast(list[dict[str, Any]], table.to_pylist())
        if len(split_rows) != source.row_count:
            raise ValueError(
                f"prepared {split} row count changed: manifest {source.row_count}, "
                f"loaded {len(split_rows)}"
            )
        rows.extend(split_rows)
    return rows


def _resolve_tokenizer_assets(sft_config: Mapping[str, Any]) -> TokenizerTrace:
    from fedbrew.data.oasst1_sft import _resolve_tokenizer_assets as resolve

    return resolve(sft_config)


def _load_tokenizer(trace: TokenizerTrace) -> Any:
    from fedbrew.data.oasst1_sft import _load_tokenizer as load

    return load(trace)


def _eos_token_id(tokenizer: Any) -> int:
    eos = getattr(tokenizer, "eos_token_id", None)
    if eos is None:
        raise ValueError("prepared tokenizer does not define an EOS token")
    return int(eos)


def _require_offline(sft_config: Mapping[str, Any]) -> None:
    if not bool(sft_config.get("local_files_only", True)):
        raise ValueError("generic_sft requires local_files_only: true")
    if bool(sft_config.get("trust_remote_code", False)):
        raise ValueError("generic_sft requires trust_remote_code: false")


def _parse_split_ratios(value: object) -> tuple[float, float, float]:
    if value is None:
        return DEFAULT_SPLIT_RATIOS
    config = _mapping(value, "tree_splits")
    ratios = (
        float(config.get("train_ratio", DEFAULT_SPLIT_RATIOS[0])),
        float(config.get("client_eval_ratio", DEFAULT_SPLIT_RATIOS[1])),
        float(config.get("global_test_ratio", DEFAULT_SPLIT_RATIOS[2])),
    )
    if any(ratio <= 0.0 for ratio in ratios) or abs(sum(ratios) - 1.0) > 1e-9:
        raise ValueError("tree_splits ratios must be positive and sum to 1.0")
    return ratios


def _client_ids(
    selected: Sequence[str],
    mapping: FieldMapping,
) -> dict[str, str]:
    """Map each selected group name to its client id, refusing a collision.

    _safe_client_id folds case and turns every run of non-alphanumerics into a
    single underscore, so "Anatomy" and "anatomy", or "Skin" and "Skin ", or
    "A-B" and "A B", all produce the same id. Nothing checked: the second
    shard overwrote the first, clients.jsonl carried two rows with the same id,
    and the loop then trained the one surviving shard twice a round under two
    separate FedAvg weights while the client it belonged to vanished.
    """

    ids: dict[str, str] = {}
    owners: dict[str, str] = {}
    collisions: list[tuple[str, str, str]] = []
    for client_key in selected:
        client_id = (
            anonymize_client_id(client_key)
            if mapping.anonymize_client_ids
            else _safe_client_id(client_key)
        )
        if client_id in owners:
            collisions.append((client_id, owners[client_id], client_key))
            continue
        owners[client_id] = client_key
        ids[client_key] = client_id

    if collisions:
        detail = "; ".join(
            f"{first!r} and {second!r} both become {client_id!r}"
            for client_id, first, second in collisions
        )
        raise ValueError(
            f"{len(collisions)} client id collision(s): {detail}. Group names "
            "are folded to lowercase and every run of non-alphanumerics becomes "
            "one underscore, so distinct groups can share an id; the shards "
            "would overwrite each other. Set "
            "generic_sft.anonymize_client_ids: true, or make the group values "
            "distinct under that folding."
        )
    return ids


def _safe_client_id(client_key: str) -> str:
    """Return a readable, filesystem-safe client id for a public group name."""

    cleaned = "".join(
        character if character.isalnum() else "_" for character in client_key.strip()
    ).strip("_")
    while "__" in cleaned:
        cleaned = cleaned.replace("__", "_")
    if not cleaned:
        raise ValueError("client key produced an empty identifier")
    return f"client_{cleaned.lower()}"


def _mapping(value: object, name: str) -> Mapping[str, Any]:
    if value is None:
        return {}
    if not isinstance(value, Mapping):
        raise ValueError(f"{name} must be a mapping")
    return cast(Mapping[str, Any], value)


def _required_text(config: Mapping[str, Any], name: str) -> str:
    value = config.get(name)
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"generic_sft.{name} is required")
    return value


def _positive_int(value: object, name: str) -> int:
    if isinstance(value, bool) or not isinstance(value, int) or value <= 0:
        raise ValueError(f"{name} must be a positive integer")
    return value


def _fraction(value: object) -> float | None:
    if value is None:
        return None
    if isinstance(value, bool) or not isinstance(value, int | float):
        raise ValueError("caps.train_fraction must be a number in (0, 1]")
    number = float(value)
    if not 0.0 < number <= 1.0:
        raise ValueError("caps.train_fraction must be in (0, 1]")
    return number


def _optional_positive_int(value: object) -> int | None:
    if value is None:
        return None
    if isinstance(value, bool) or not isinstance(value, int) or value <= 0:
        raise ValueError("cap values must be positive integers or null")
    return value


def _text_or_none(value: object) -> str | None:
    if value is None:
        return None
    text = str(value).strip()
    return text or None


__all__ = [
    "GenericSFTGenerationSummary",
    "generate_generic_sft_from_config",
    "render_template",
    "resolve_choice_fields",
]
